name: dotnet-docker-example-ci

on:
  push:
    branches:
      - feature/dotnet-docker-example

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and test
        uses: docker/build-push-action@v6
        with:
          target: build
          file: dotnet/Dockerfile
          load: true
          build-args: DEBUG=true

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          target: final
          file: dotnet/Dockerfile
          tags: ${{ vars.DOCKER_USERNAME }}/${{ github.event.repository.name }}:latest